version: 0.0.{build}

branches:
  except: 
  - gh-pages

image: Visual Studio 2017

before_build:
 - nuget restore
 
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

test: off
test_script:
  - vstest.console /logger:Appveyor "C:\projects\sqe\test\SQE.CSharp.UnitTests\bin\Debug\netcoreapp2.0\SQE.CSharp.UnitTests.dll"

artifacts:
 - path: '**\*.nupkg'
   name: NuGet

for:
-
  branches:
    only:
      - develop
  version: 0.0.{build}-preview
  
-
  branches:
    only:
      - feature/.*/
  version: 0.0.{build}-{branch}-preview
