version: 0.0.{build}+{branch}

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
  
branches:
  except: 
  - gh-pages

image: Visual Studio 2017

before_build:
 - nuget restore
 
artifacts:
 - path: '**\*.nupkg'
   name: NuGet
