version: 0.0.{build}+{branch}

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
  
branches:
  except: 
  - gh-pages

image: Visual Studio 2017

before_build:
 - nuget restore
 
artifacts:
 - path: '**\*.nupkg'
   name: NuGet
